# The interactive app, packaged so it runs the same way on any machine.
#
#   docker build -t where-you-refuel .
#   docker run --rm -p 8501:8501 -v "$(pwd)/data":/app/data:ro where-you-refuel
#
# The data directory is deliberately *not* baked in: data/raw alone is 856 MB of
# MIMIT extracts, it is regenerated by the pipeline, and it is gitignored. It is
# mounted at runtime instead — see docker-compose.yml.

FROM python:3.12-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    MPLCONFIGDIR=/tmp/matplotlib

# Requirements first, and on their own layer: editing app.py must not force a
# reinstall of pandas and matplotlib.
COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

COPY app.py ./
COPY scripts/ ./scripts/
COPY .streamlit/ ./.streamlit/

# UID 1000 matches the first ordinary user on a typical Linux host, so files the
# pipeline service writes into the bind-mounted data/ and figures/ come back
# owned by you rather than by root. Override with `user:` in compose if your own
# uid differs (`id -u`).
RUN useradd --create-home --uid 1000 app && \
    mkdir -p data/raw data/interim data/processed figures && \
    chown -R app:app /app
USER app

EXPOSE 8501

# Streamlit answers /_stcore/health once the server is actually serving, which
# is a stronger signal than "the process started".
HEALTHCHECK --interval=30s --timeout=5s --start-period=30s --retries=3 \
    CMD python -c "import urllib.request as u; exit(0 if u.urlopen('http://localhost:8501/_stcore/health', timeout=3).status == 200 else 1)"

# 0.0.0.0, not localhost: a server bound to the loopback inside the container is
# unreachable from the host even with -p.
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
